import "./globals.css";
import { Metadata } from "next";
// const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
	title: {
		absolute: "",
		default: "Next.js Learning-- Shafkat63",
		template: "%s | Shafkat63",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header
					style={{
						backgroundColor: "lightblue",
						padding: "1rem",
						justifyContent: "center",
						alignItems: "center",
						display: "flex",
					}}
				>
					<p>Header</p>
				</header>
				{children}
				<footer
					style={{
						backgroundColor: "ghostwhite",
						padding: "1rem",
						justifyContent: "center",
						alignItems: "center",
						display: "flex",
					}}
				>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
