import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header
					style={{
						backgroundColor: "lightblue",
						padding: "1rem",
						justifyContent: "center",
						alignItems: "center",
						display: "flex",
					}}
				>
					<p>Header</p>
				</header>
				{children}
				<footer
					style={{
						backgroundColor: "ghostwhite",
						padding: "1rem",
					}}
				>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
